name       : python-joblib
version    : 1.1.0
release    : 5
source     :
    - https://github.com/joblib/joblib/archive/refs/tags/1.1.0.tar.gz : 4cda464ca712a4814849c9477d7551b696ce215dc05d79fc516460814ef48f4f
license    : BSD-3-Clause
component  : programming.python
summary    : Computing with Python functions
description: |
    Joblib is a set of tools to provide lightweight pipelining in Python.
    In particular: - transparent disk-caching of functions and lazy re-evaluation (memoize pattern)
    - easy simple parallel computingJoblib is optimized to be fast and robust on large data in particular and has specific optimizations for numpy arrays.
build      : |
    %python3_setup
install    : |
    %python3_install
