name       : python-joblib
version    : 0.13.2
release    : 1
source     :
    - https://github.com/joblib/joblib/archive/0.13.2.tar.gz : 1a45a4d8d3728245a941946e0741cbfb7822c5a91cf5fbad3b3efbe2b27050ae
license    : BSD-3-Clause
component  : programming.python
summary    : Computing with Python functions
description: |
    Joblib is a set of tools to provide lightweight pipelining in Python. In particular: 
    - transparent disk-caching of functions and lazy re-evaluation (memoize pattern)
    - easy simple parallel computing

    Joblib is optimized to be fast and robust on large data in particular and has specific optimizations for numpy arrays.
build      : |
    %python3_setup
install    : |
    %python3_install