name       : python-joblib
version    : 1.0.1
release    : 3
source     :
    - https://github.com/joblib/joblib/archive/refs/tags/1.0.1.tar.gz : c930c58f0deacd22c525a64c4ba937b521dcb77493d5887b75bb4d204aa61a26
license    : BSD-3-Clause
component  : programming.python
summary    : Computing with Python functions
description: |
    Joblib is a set of tools to provide lightweight pipelining in Python.
    In particular: - transparent disk-caching of functions and lazy re-evaluation (memoize pattern)
    - easy simple parallel computingJoblib is optimized to be fast and robust on large data in particular and has specific optimizations for numpy arrays.
build      : |
    %python3_setup
install    : |-
    %python3_install
